# Generated by Django 5.2.10 on 2026-01-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ['order_index']},
        ),
        migrations.RenameField(
            model_name='coursemodule',
            old_name='order',
            new_name='order_index',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='coursemodule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('QURAN', 'Quran'), ('TAJWEED', 'Tajweed'), ('ARABIC', 'Arabic Language'), ('TAFSIR', 'Tafsir'), ('HIFZ', 'Hifz (Memorization)'), ('FIQH', 'Fiqh'), ('AQEEDAH', 'Aqeedah')], default='QURAN', max_length=20),
        ),
    ]
