# Generated by Django 5.2.10 on 2026-01-23 13:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursemodule_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='courses',
                to='users.teacherprofile',
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Duration'), ('SUBSCRIPTION', 'Subscription Based')], default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_weeks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='learning_objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_reference',
            field=models.TextField(blank=True, help_text='URL or content identifier'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_free_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='requires_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('LIVE', 'Live Session'), ('READING', 'Reading Material'), ('QUIZ', 'Quiz')], default='READING', max_length=20),
        ),
    ]
