# Generated by Django 5.2.10 on 2026-01-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_pass_percent_certificate_courseannouncement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a file (PDF, Video) for this module that can be dissected into lessons.', null=True, upload_to='modules/files/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_marker',
            field=models.CharField(blank=True, help_text='End point in the module file', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_marker',
            field=models.CharField(blank=True, help_text='Start point in the module file (e.g., page number or timestamp)', max_length=50),
        ),
    ]
