# Generated by Django 5.2.10 on 2026-07-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursemodule_file_lesson_end_marker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
