# Generated by Django 5.2.10 on 2026-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionbooking",
            name="payment_status",
            field=models.CharField(choices=[("UNPAID", "Unpaid"), ("PAID", "Paid"), ("REFUNDED", "Refunded")], default="UNPAID", max_length=20),
        ),
        migrations.AddField(
            model_name="sessionbooking",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
