# Generated by Django 5.2.10 on 2026-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_sessionbooking_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionbooking",
            name="payment_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionbooking",
            name="session_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="sessionbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("APPROVED", "Approved"),
                    ("CONFIRMED", "Confirmed"),
                    ("DECLINED", "Declined"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="REQUESTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sessionbooking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Unpaid"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("EXPIRED", "Expired"),
                    ("REFUNDED", "Refunded"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
    ]
