# Generated by Django 5.2.10 on 2026-02-11 00:00

from django.db import migrations


def migrate_statuses(apps, schema_editor):
    SessionBooking = apps.get_model("users", "SessionBooking")
    SessionBooking.objects.filter(status="PENDING").update(status="REQUESTED")


def reverse_statuses(apps, schema_editor):
    SessionBooking = apps.get_model("users", "SessionBooking")
    SessionBooking.objects.filter(status="REQUESTED").update(status="PENDING")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_booking_payment_window_and_link"),
    ]

    operations = [
        migrations.RunPython(migrate_statuses, reverse_statuses),
    ]
