# Generated by Django 5.2.10 on 2026-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_migrate_booking_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionbooking",
            name="session_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
