# Generated by Django 5.2.10 on 2026-02-11 00:00

from django.db import migrations


def normalize_statuses(apps, schema_editor):
    SessionBooking = apps.get_model("users", "SessionBooking")
    # Legacy PENDING -> REQUESTED
    SessionBooking.objects.filter(status="PENDING").update(status="REQUESTED")
    # Legacy confirmed but unpaid -> APPROVED (awaiting payment)
    SessionBooking.objects.filter(status="CONFIRMED", payment_status="UNPAID").update(status="APPROVED")


def reverse_statuses(apps, schema_editor):
    SessionBooking = apps.get_model("users", "SessionBooking")
    SessionBooking.objects.filter(status="REQUESTED").update(status="PENDING")
    SessionBooking.objects.filter(status="APPROVED", payment_status="UNPAID").update(status="CONFIRMED")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_session_link_nullable"),
    ]

    operations = [
        migrations.RunPython(normalize_statuses, reverse_statuses),
    ]