# Generated by Django on 2026-02-11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_normalize_booking_statuses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionbooking",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="sessionbooking",
            name="paid_at",
        ),
        migrations.RemoveField(
            model_name="sessionbooking",
            name="payment_due_at",
        ),
        migrations.RemoveField(
            model_name="sessionbooking",
            name="session_link",
        ),
    ]
