# Generated by Django 5.2.10 on 2026-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_booking_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Legacy)'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20),
        ),
    ]
