# Generated by Django 5.2.10 on 2026-02-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_sessionbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
