# Generated by Django 5.2.10 on 2026-02-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_sessionbooking_status_bookingorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
