# Generated by Django 5.2.10 on 2026-02-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_status_to_bookingorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingorder',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
