# Generated by Django 5.2.10 on 2026-06-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_bookingorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingorder',
            name='booking_type',
            field=models.CharField(choices=[('SINGLE', 'Single Session'), ('BATCH', 'Batch/Recurring')], default='SINGLE', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='is_paid_to_teacher',
            field=models.BooleanField(default=False, help_text='True when the admin has released escrow funds to the teacher for this completed session.'),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Jitsi meeting room URL', null=True),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Legacy)'), ('REQUESTED', 'Requested'), ('RESERVED', 'Reserved (Awaiting Payment)'), ('APPROVED', 'Approved'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20),
        ),
    ]
