# Generated by Django 5.2.10 on 2026-06-28 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_bookingorder_booking_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_booked', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slot', to='users.sessionbooking')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='users.teacherprofile')),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['teacher', 'start_time'], name='users_times_teacher_9dd6d7_idx'), models.Index(fields=['teacher', 'is_booked'], name='users_times_teacher_964b45_idx')],
                'unique_together': {('teacher', 'start_time')},
            },
        ),
    ]
