# Generated by Django 5.2.10 on 2026-06-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='batch_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='batch_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
