# Generated by Django 5.2.10 on 2026-06-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_timeslot_batch_end_date_timeslot_batch_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingorder',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='sessionbooking',
            name='is_paid_to_teacher',
        ),
        migrations.RemoveField(
            model_name='sessionbooking',
            name='meeting_url',
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Legacy)'), ('REQUESTED', 'Requested'), ('RESERVED', 'Reserved (Awaiting Payment)'), ('APPROVED', 'Approved'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20),
        ),
    ]
