# Generated by Django 5.2.10 on 2026-06-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_bookingorder_booking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='allowed_booking_type',
            field=models.CharField(choices=[('SINGLE', 'Single Booking Only'), ('RANGE', 'Range Booking Only'), ('BOTH', 'Both Single & Range')], default='BOTH', max_length=10),
        ),
    ]
