# Generated by Django 5.2.10 on 2026-07-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_timeslot_allowed_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Legacy)'), ('REQUESTED', 'Requested'), ('RESERVED', 'Reserved (Awaiting Payment)'), ('APPROVED', 'Approved'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='REQUESTED', max_length=20),
        ),
    ]
