# Generated by Django 5.2.10 on 2026-09-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_supported_bank_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionattendance',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sessionexcuse',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacherpayoutledger',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacherpayoutledger',
            name='payout_reference',
            field=models.CharField(blank=True, help_text='Bank transaction reference, receipt number, or FT transfer code', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='audition_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='payout_account_holder',
            field=models.CharField(blank=True, help_text='Account holder legal full name', max_length=150),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='payout_account_number',
            field=models.CharField(blank=True, help_text='Bank account number or mobile money number', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='payout_bank_name',
            field=models.CharField(blank=True, help_text='e.g. Commercial Bank of Ethiopia (CBE), Telebirr, Awash Bank', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='payout_phone',
            field=models.CharField(blank=True, help_text='Contact telephone for payout confirmation', max_length=50),
        ),
    ]
