#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export DJANGO_SETTINGS_MODULE="${DJANGO_SETTINGS_MODULE:-config.settings.production}"


python /app/manage.py migrate --noinput

python /app/manage.py setup_admin || true

python /app/manage.py collectstatic --noinput

exec gunicorn config.asgi --bind "0.0.0.0:${PORT:-5000}" --chdir=/app -k uvicorn_worker.UvicornWorker --workers 2 --timeout 120
