# Generated by Django 5.2.10 on 2026-02-11 14:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_alter_sessionbooking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_checkout_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID (available after checkout)', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in the currency (e.g., 50.00)', max_digits=10)),
                ('currency', models.CharField(default='etb', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('booking', models.OneToOneField(help_text='The booking this payment is for.', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='users.sessionbooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
