# Generated by Django 5.2.10 on 2026-02-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0012_alter_sessionbooking_status_bookingorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(default=1, help_text='The order this payment is for.', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='users.bookingorder'),
            preserve_default=False,
        ),
    ]
