# Generated by Django 5.2.10 on 2026-09-13 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_general_category_field'),
        ('payments', '0002_remove_payment_booking_payment_order'),
        ('users', '0024_supported_bank_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_enabled', models.BooleanField(default=True, help_text='Toggle Stripe (International cards) ON/OFF.')),
                ('chapa_enabled', models.BooleanField(default=True, help_text='Toggle Chapa (Telebirr, CBE Birr, Awash, local cards) ON/OFF.')),
                ('manual_bank_enabled', models.BooleanField(default=True, help_text='Toggle Manual / Direct Bank Transfer & Telebirr ON/OFF.')),
                ('manual_verification_mode', models.CharField(choices=[('MANUAL_ADMIN', 'Manual Admin Approval'), ('SHEGER_API', 'Automated Sheger API Verification')], default='MANUAL_ADMIN', help_text='Whether bank/Telebirr transfers require manual staff approval or automated Sheger API validation.', max_length=30)),
                ('chapa_public_key', models.CharField(blank=True, default='', help_text='Chapa Public Key (CHAPUBK_...). Fallback to settings if blank.', max_length=255)),
                ('chapa_secret_key', models.CharField(blank=True, default='', help_text='Chapa Secret Key (CHASECK_...). Fallback to settings if blank.', max_length=255)),
                ('chapa_webhook_secret', models.CharField(blank=True, default='', help_text='Chapa Webhook Secret hash for verifying callback signatures.', max_length=255)),
                ('sheger_api_key', models.CharField(blank=True, default='', help_text='API Key / Token for Sheger API automated transaction validation.', max_length=255)),
                ('sheger_api_url', models.CharField(blank=True, default='https://api.shegerpay.com', help_text='Base URL for Sheger verification service.', max_length=255)),
                ('bank_accounts', models.JSONField(blank=True, default=list, help_text='List of bank/telebirr accounts for manual transfers. Format: [{"bank_name": "CBE", "account_number": "1000...", "account_name": "Risala", "icon": "account_balance"}]')),
                ('manual_payment_instructions', models.TextField(blank=True, default='Please transfer the exact amount to one of our official accounts, then enter your transaction reference number.', help_text='Instructions displayed to students on the Bank Transfer page.')),
            ],
            options={
                'verbose_name': 'Payment Gateway Configuration',
                'verbose_name_plural': 'Payment Gateway Configuration',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_note',
            field=models.TextField(blank=True, default='', help_text='Staff notes for manual approval or rejection.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, default='', help_text='Bank or wallet name used (e.g. CBE, Telebirr).', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='chapa_reference',
            field=models.CharField(blank=True, help_text='Chapa transaction reference', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course this payment is for (if purchasing a course).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='payment',
            name='manual_receipt_image',
            field=models.ImageField(blank=True, help_text='Uploaded transfer receipt screenshot.', null=True, upload_to='payments/receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='manual_transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID / Reference entered by customer for bank/Telebirr transfer.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'Stripe (Card)'), ('CHAPA', 'Chapa (Telebirr / CBE Birr)'), ('MANUAL_BANK', 'Bank Transfer / Telebirr')], default='STRIPE', help_text='The payment method/gateway used.', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(blank=True, help_text='Unique transaction reference for tracking across gateways.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who made the payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.CharField(choices=[('WEBHOOK', 'Automated Webhook'), ('MANUAL_ADMIN', 'Manual Admin Approval'), ('SHEGER_API', 'Sheger API'), ('AUTO_BYPASS', 'Free / Auto Bypass')], default='WEBHOOK', help_text='How this payment was verified.', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The order this payment is for (if booking sessions).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.bookingorder'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255, null=True),
        ),
    ]
