# Generated by Django on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentgatewayconfig_payment_admin_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sheger_status',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Status returned by ShegerPay (e.g. verified, failed, invalid_input, network_error).',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='sheger_reason',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Detailed reason or error message returned by ShegerPay automated check.',
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='sheger_response',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Raw JSON response from ShegerPay API.',
            ),
        ),
    ]
